site_name: Cloud.ru Evolution Terraform Provider

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
    
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer

markdown_extensions: 
  - attr_list
  - md_in_html
    
