site_name: Cloud.ru Evolution Terraform Provider

nav:
  - Знакомство с Terraform: index.md
  - Обратная связь: feedback.md

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
    
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer

markdown_extensions: 
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
    
