site_name: Cloud.ru Evolution Terraform Provider

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
markdown_extensions: 
  - attr_list
  - md_in_html
    
